### ISSUE TITLE
 Make blurr target python 3.5 (instead of 3.6)

### ISSUE THREAD

**Issue by prashastk** [productml/blurr#113]

**Comment by indradeep** [comment]
3.6 has seen some great feature additions, some of which I believe we are using - like Type annotations for lists.  Full changelog here: https://docs.python.org/3/whatsnew/3.6.html

Let's take a deeper look at what else 3.6 has added.   3.6 was released greater than 1 year ago... so I don't see the merits of supporting further back.

**Comment by prashastk** [comment]
Okay. Don't think there is a point in us looking into this now unless someone requests 3.5 support. Happy to defer to that point.
