### ISSUE TITLE
'Anchor: 'None' is not a anchor' needs a better error message

### ISSUE THREAD

**Issue by roy100** [productml/blurr#138]
I did this: 

```
Anchor:
  
Condition:  offer_ai_v1.game_stats.offer_type != '
```
and transform threw an error: `Anchor: 'None' is not a anchor`

It should have been 

```
Anchor:
  Condition:  offer_ai_v1.game_stats.offer_type != '
```

`Anchor condition not found` would be a better error message for this case

**Comment by vigbk** [comment]
We will have to fork the library and create custom exceptions.
