### ISSUE TITLE
prepare tutorial examples for distribution

### ISSUE THREAD

**Issue by mserranom** [productml/blurr#145]
Examples from tutorial should be made available for experimentation. Options:

* Produce a downloadable zip with the examples
* Allow the CLI to consume the examples from `http`
* Prepare a Jupyter notebook that mimics CLI

**Comment by prashastk** [comment]
It would also be good if we run the examples as part of the unit tests. That way we will always keep them updated.

**Comment by mserranom** [comment]
@prashastk this is https://github.com/productml/blurr/issues/70
