### ISSUE TITLE
YAML validation fails for valid Python expressions that are invalid YAML

### ISSUE THREAD

**Issue by roy100** [productml/blurr#167]
This is expected behavior, but falls short of our claim that users can write `any python expression` and is currently breaking the fbt example. 

Examples: 

**Function arguments**

`Value: sorted(last_24_hours.products_bought.extend(next_24_hours.products_bought), key=itemgetter(1), reverse=True)[:3]`

Running `blurr validate` fails with `DataGroups.3.Fields.0.Value: 'sorted(last_24_hours.products_bought.extend(next_24_hours.products_bought), key=itemgetter(1), reverse=True)[:3]' sets value using `=`.` even though the usage of = is correct within the sorted function

**Mapping values**
`Value: sorted(last_24_hours.products_bought.extend(next_24_hours.products_bought), key=lambda x: x[1], reverse==True)[:3]` is another way to write the sorted function but it is not a valid YAML. 

yamllint.com throws a validation error `(<unknown>): mapping values are not allowed in this context at line 82 column 103` - the culprit being `key=lambda x: x[1]`  (Blurr validation fails too but doesn't show the problem). 

There are likely to be many other situations where Python expressions will lead to failed YAML validation - do we need a bigger strategy for how to handle this?

**Comment by roy100** [comment]
Fbt files are in examples\frequently-bought-together

**Comment by prashastk** [comment]
#169 fixes the first point.

For the second point (with the first fix) you can just enclose the expression in quotes to get around the YAML issue caused by ':' in 'lambda x: x[1]'
`
"sorted(last_24_hours.products_bought.extend(next_24_hours.products_bought), key=lambda x: x[1], reverse==True)[:3]"
`
