### ISSUE TITLE
WindowAggregate should not need window definition 

### ISSUE THREAD

**Issue by roy100** [productml/blurr#170]
The fbt example does a window operation by combining 2 windows but fails because the WindowAggregate expects WindowType and WindowValue to be present for each WindowAggregate

**Comment by prashastk** [comment]
Discussed with @indradeep . We should use Blurr:DataGroup:IdentityAggregate for this purpose. WindowAggregate without a window would be a bit meaningless. Just replacing the type to IdentityAggregate should be sufficient for that use case.
