### ISSUE TITLE
Prediction end point

### ISSUE THREAD

**Issue by roy100** [productml/blurr#20]
Once the data is in s3 and dynamo, we are not clear about how the prediction flow will work. We are assuming that the user will setup the model server themselves. There needs to be an intermediary that takes in a user ID, queries dynamo etc for the features and then queries the model server. We need to think through how a user will set this up and what can we do to make this bit easier

**Comment by indradeep** [comment]
Vignesh wrote the document to walk through the process.  This is deferred to much later in the project lifecycle.
