### ISSUE TITLE
Add a data processor abstraction to process raw data and convert it into a list of Records in the runners.

### ISSUE THREAD

**Issue by prashastk** [productml/blurr#203]
This is to convert one line in the raw data to the format that blurr understands (as the Record class).

The simple case is when the input file has one json dict per line that corresponds to one event. For more complex cases one input line could correspond to multiple events (like in ipfix format). The data processor is an abstraction to handle that in the runner.

**Comment by mserranom** [comment]
could you add more info please?

**Comment by prashastk** [comment]
@mserranom added more info and updated the title.
