### ISSUE TITLE
Identity for features generated in BlockAggregate?

### ISSUE THREAD

**Issue by mserranom** [productml/blurr#217]
**I certify I'm including:**

- [x] A descriptive title
- [x] A description of the problem I'm trying to solve, including *why* I think this is a problem
- [ ] An overview of the suggested solution
- [ ] If the feature changes current behaviour, reasons why my solution is better

### Scenario

We serve different difficulty modes for a game. A user always plays in the same difficulty model.

We we want to predict how many purchases the user will make.

### Events

Every time the user plays a round, we receive an event of this shape:

| user_id | country | purchase | difficulty_mode | 
|--------|---------|-------------------|-----------------|
|ht83nx|US|true|3|

### Transformation

| user_id | country | total_purchases | difficulty_mode | total_rounds_played |
|--------|---------|-----------------|-----------------|---------------------|
|ht83nx|US|12|3|410|

### DTC?

This is a very naive, but potential scenario. In order to execute this transformation theoretically  the operations supported by a `BlockAggregate` in a Streaming DTC should suffice.

But we also need to indicate that `user_id` is the Identity for such features. So far, we set the Identity in a Streaming DTC so it's used subsequently in a Window DTC. The output of a BlockAggregate won't have unique entries by Identity. 

But this is a different case. We require the Identity to be unique, so we can use the result for prediction.

How could we approach this problem? is there anything missing?

**Comment by prashastk** [comment]
I don't quite understand what the problem is. Why wouldn't the output of BlockAggregate not have unique entries by identity?

**Comment by mserranom** [comment]
`Why wouldn't the output of BlockAggregate not have unique entries by identity?`

I may be doing some wrong assumptions here, please correct me if so:

It's not that it __won't__ have unique entries. They will be unique, because _I wrote the aggregate that way_. It's about whether the DTC can  **guarantee** that they will be unique.

For the tutorial example:

- the Streaming DTC defines `user_id` as Identity
- The Streaming DTC produces session aggregates
-  session aggregates are time-aggregated by the Window DTC. 
- Because `user_id` is the Identity in the Streaming DTC, it is **guaranteed** that in the Window aggregation `user_id` is unique per row. 

For the example I posted before, in order to use the aggregation result as features, we **must** have unique `user_id`. In the tutorial example, the result of the Streaming DTC **does not** have unique values for the `user_id` identity. 

Is there something to play with Identity, so I can guarantee the resulted transformation can be used as features, with unique `user_id`?

**Comment by prashastk** [comment]
I think the confusion is around the output of Window DTC. That need not be restricted to one per user. For each user it would contain one row every-time the anchor condition is met. For e.g. if someone is making an ad click prediction model then the training data for it would contain data per ad shown and one user could have been shown multiple ads over many days. In this case you would have multiple rows for a user after the window DTC operation.

**Comment by mserranom** [comment]
Got it! Finally. I'd like at some point to reflect my train of thought in the documentation. Closing for the time being.
