### ISSUE TITLE
Allow users to use their own data processor classes

### ISSUE THREAD

**Issue by vigbk** [productml/blurr#224]
**I certify I'm including:**

- [x] A descriptive title
- [x] A description of the problem I'm trying to solve, including *why* I think this is a problem
- [x] An overview of the suggested solution
- [ ] If the feature changes current behaviour, reasons why my solution is better

**Problem**
To add your own data processor class, you would have to create a pull request with your custom data processor and wait for it to be merged into the library. Users should be able to use their own data processors without having to change the library.

**Solution**
Have a method to register a data processor class within the Blurr library. The user can provide a name for their data processor when they register. The CLI will use the name to load their data processor into the runner.

**Comment by prashastk** [comment]
@vigbk As discussed the user is expected to use the SparkRunner in their own code which takes in a DataProcessor. CLI is just a demonstration of how it works.

Closing this issue. Feel free to re-open if you think we should add it.
