### ISSUE TITLE
Update docs (DTC snippets.md) to explain how to use custom functions

### ISSUE THREAD

**Issue by roy100** [productml/blurr#226]
**I certify I'm including:**

- [ ] A descriptive title
- [ ] A description of the problem I'm trying to solve, including *why* I think this is a problem
- [ ] An overview of the suggested solution
- [ ] If the feature changes current behavior, reasons why my solution is better

Docs need to be updated as a result of #58

**Comment by prashastk** [comment]
Duplicate of #208
