### ISSUE TITLE
How does a user install and play around with Blurr

### ISSUE THREAD

**Issue by roy100** [productml/blurr#23]
Before a user hooks up their raw data and starts training a model, we need an easy way for the user to install and play around with Blurr. We need to figure out how they do that. 

This is a critical step (well, all steps are critical) in the customer acquisition funnel. 

Hear about Blurr > Go to Github project > Install and play around > ML dev > Use in production

Some ideas: Do we have a demo AWS account with raw data? A tutorial? A local stack that can be deployed with pre-populated dummy data?

**Comment by mserranom** [comment]
Discussion: https://docs.google.com/document/d/1rbmxufKVCN_TSMm9gwICqpZdAF9__19jYyABIo75Geg/edit?ts=5ab42060#

**Comment by indradeep** [comment]
Accepted.  Development in progress on another issue.
