### ISSUE TITLE
Blurr Playground: A jupyter notebook with a full example featuring BTS and Sample Data

### ISSUE THREAD

**Issue by indradeep** [productml/blurr#232]
#### Issue Checklist:
- [x] Descriptive title
- [x] Completed sections below

### Problem Description
Our examples are static and showcase how different problems can be solved using Blurr.  However, when one wants to try out Blurr hands-on they need to go though the full project setup before they can start tinkering with the Blurr Transform Spec.  The friction in the process adds a huge impedance to adoption.

### Solution Proposal
Examples should be provided in the form of a Jupyter Notebook.  A notebook allows the context of the problem being solved, the solution details, etc. to be specified in markdown blocks.  The user can simply execute blocks to load the BTS and transform the sample data included.

Expected behavior:
1. Launch Notebook
2. Read through the descriptors
3. Walks though the BTS yaml
4. Validate BTS
5. Run BTS on sample data
6. Observe and compare results with documentation block
7. Follow instructions to make changes to BTS
8. Run modified BTS on sample data
9. Verify results

The Notebook should provide the following:
1. Full environment with the latest Blurr package, Sample Data and BTS.
2. Must be a fresh environment at launch - changes made by each user must be limited to their own kernel

### Impact on current behavior
This is an extension to what we already have.  All changes are expected to improve usability.

**Comment by prashastk** [comment]
@indradeep What is BTS? :)
