### ISSUE TITLE
Prefix a _ to all methods in item classes

### ISSUE THREAD

**Issue by prashastk** [productml/blurr#233]
**I certify I'm including:**

- [x] A descriptive title
- [x] A description of the problem I'm trying to solve, including *why* I think this is a problem
- [x] An overview of the suggested solution
- [ ] If the feature changes current behaviour, reasons why my solution is better

Currently if an aggregate defines a field called `execute` (or any of the other methods we have in the item classes) the evaluation code will return the` execute method` as opposed to the `execute field`. To prevent this kind of a problem all methods and variables should start with _ (even if they are not private) so as the completely separate out the namespace of internal names.

We already don't support `Field` names starting with _ for this very problem.

**Comment by mserranom** [comment]
Another option is to use the [Delegation](https://en.wikipedia.org/wiki/Delegation_pattern) pattern.

Pros:
- No identifier hacking
- Cleaner interface and separation of responsibilities between descriptor and executor. A consequence is easier testability.

Cons:
- Extra layer of indirection
- Not idiomatic python perhaps?

**Comment by prashastk** [comment]
@mserranom I am not sure how this solves the problem. Can you demonstrate with a small example?

**Comment by prashastk** [comment]
We don't pass members explicitly to the evaluation context. The access happens via `.` which internally calls `__getattr__` (after trying `__getattribute__`). The Aggregate class overrides `__getattr__` to return the field's value based on field member being referenced.

In the case of `execute` and other member functions / variables  Python first calls `__getattribute__` which would return a reference to them. So, a field with the name of `execute` will never get evaluated. The same `__getattribute__` function gets called when a member is accessed by regular python code as well.

To disambiguate these two we need to have mutually exclusive naming to ensure that there is no clash between them.

**Comment by mserranom** [comment]
Thanks for the clarification. I've just dug into that code, makes sense!
