### ISSUE TITLE
blurr.ai page: bad link of Example

### ISSUE THREAD

**Issue by ForzaGreen** [productml/blurr#286]
In [blurr.ai](http://blurr.ai/) the **Example** link  (at the top right hand corner) points to a bad URL:
`https://github.com/productml/blurr/blob/master/examples/offer-ai/offer-ai-walkthrough.md` => 404 Error.
The correct URL is: 
`https://github.com/productml/blurr/blob/master/docs/examples/offer-ai/offer-ai-walkthrough.md`

**Comment by mserranom** [comment]
Thanks for the report @ForzaGreen

**Comment by roy100** [comment]
Thank you @ForzaGreen, we have fixed the example link. It now points to a Jupyter Notebook that has a live playground with NYSE stock data. 

https://mybinder.org/v2/gh/productml/blurr/master?filepath=docs%2Fexamples%2Fnyse (might take a while to load, we're working on replacing it with something faster #282). 

Do take a look and let us know, we would love your feedback!
