### ISSUE TITLE
Enable mypy

### ISSUE THREAD

**Issue by mserranom** [productml/blurr#35]
Mypy is disabled in `build.sh` since the initial code already had plenty of typing errors.

We need to:

- Fix all syntax error
- Enable mypy in `build.sh`
- decide the set of mypy configuration parameters we'll use for validation

**Comment by prashastk** [comment]
@vigbk can you link to the one pager you have written and close this?

**Comment by vigbk** [comment]
This document discusses the mypy issues https://docs.google.com/document/d/1EL-Luwo5UDDVd4jY9l8bpdMEl_F1TNTKAl117Aw0QX8/edit. We can revisit this later once mypy becomes more mature. Closing for now.
