### ISSUE TITLE
Create Blurr Configuration File 

### ISSUE THREAD

**Issue by indradeep** [productml/blurr#59]
The Blurr configuration file should be read from disk / before execution.  Here is how config can be specified:

- CLI
- ~/.blurr/config.yaml

It should contain the following:

- Schema Types to Class names
- Item Types to Class name
- Custom functions path - commonly loaded for all executions
- Custom imports - loaded for ALL exeutions

**Comment by mserranom** [comment]
marked as invalid until spec agreed.

**Comment by indradeep** [comment]
This story is no longer applicable.  Design has changed.
