### ISSUE TITLE
Implement __getitem__ for BaseItemCollection to enable [] access to fields

### ISSUE THREAD

**Issue by indradeep** [productml/blurr#96]
Field names are currently restricted to python valid strings.  In the even that python valid variable names pose a restriction, the user should have the freedom to define the field names as they wish, and these field names can be accessed using the square bracket notation.

Method to implement: __getitem__
File: blurr/core/base.py
Class: BaseItemCollection

**Comment by mserranom** [comment]
Done in the board, closing here.
